### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by osseonews** [swellstores/horizon#33]
Is there a demo of this repo with a sample store showing all the features?

**Comment by ana-estrela** [comment]
@osseonews, check out the complete Horizon demo at [https://swell-horizon-demo.vercel.app/](https://swell-horizon-demo.vercel.app/). The memberships content block on the [Membership page](https://swell-horizon-demo.vercel.app/membership) is not available at present, however, you can still set up memberships using the customer groups functionality (https://www.swell.is/help/customers/customer-settings#customer-groups) and set a similar UI with our editor.
