### ISSUE TITLE
Extending categories GQL query produces an error even if model is equal to developer->models

### ISSUE THREAD

**Issue by agsmartwolf** [swellstores/horizon#38]
Hi there!

I try to expand categories query with fields "id", "parentId" and "topId":

```query getCategories {
  categories {
    results {
      name
      slug
      id             <------------ added this field
      parentId       <------------ added this field
      topId          <------------ added this field
      images {
        id
        caption
        file {
          url
          width
          height
        }
      }
      content {
        showProductsPrice
        showProductsDescription
        showFeaturedCategories
        productsPerRow
        enableQuickAdd
        featuredCategories {
          category {
            slug
            name
            description
            images {
              caption
              file {
                url
                width
                height
              }
              id
            }
          }
        }
      }
    }
  }
}
```

Everything work but "id" field.

When i'm trying to run "graphql-codegen" there is an error `pluginHelpers.isDetailedError is not a function`.
I've checked in `swell models` in admin developer panel on the web and all of these fields are presented in model.

There is the error only for field `id`.

Code is generated with fields `parentId` and `topId` and they are fetched if remove `id` field.

**Comment by rodrigoddalmeida** [comment]
Hi @agsmartwolf. The `category.id` field is not added by default in the Frontend API permissions - it should be useful to add it to our defaults, we should change that soon. Thanks for the heads up.

Meanwhile, you might find this useful if you want that field (and additional custom fields) to work as well: https://developers.swell.is/guides/opening-content-permissions

You would add something like:

```json
{
  "permissions": {
    "categories": {
      "fields": ["id"]
    }
  }
}
```

**Comment by agsmartwolf** [comment]
Hi @rodrigoddalmeida. Thank you for reply.
I've tried you said.

I've got the next response: 
```
{
  "parent_id": "store name here",
  "public": "My public key here",
  "date_created": "2022-07-10T18:07:10.902Z",
  "scope": "user",
  "revoked": false,
  "date_updated": "2023-02-23T10:49:27.961Z",
  "permissions": {
    "categories": {
      "fields": [
        "id"
      ],
      "input": {
        "fields": [
          "id"
        ]
      }
    }
  },
  "id": "internal PK here"
}
```

I've done these actions with all of my public keys.
Unfortunately i have the same error:
<img width="695" alt="Screenshot 2023-02-23 at 14 53 10" src="https://user-images.githubusercontent.com/109105178/220886722-41fffac6-b963-48c4-ac83-0e5038066154.png">

The error line is `id` line in categories.gql.

**Comment by rodrigoddalmeida** [comment]
Are you able to see `id` in the Category schema by accessing the playground? (`https://<your-store>.swell.store/playground`) 

It seems that `graphql-codegen` could provide more info on the error, but something is wrong with the package. I believe `pluginHelpers` have been substituted by the `core` package, so maybe there is a version mismatch in dependencies.

BTW, you don't generally want `input` to be set in base model permissions, as they would allow anyone to update that field.

```json
  ...,
  // Not safe
  "input": {
    "fields": [
      "id"
    ]
  }
  ...
```

**Comment by agsmartwolf** [comment]
I can see `id` in the query I've provided above by accessing the playground. It's working as expected in the playground.

I've also upgraded to the latest versions net packages:
`@graphql-codegen/introspection@latest @graphql-codegen/typescript@latest @graphql-codegen/typescript-graphql-request@latest @graphql-codegen/typescript-operations@latest`.

Still the same error.
<img width="1661" alt="Screenshot 2023-02-25 at 22 40 53" src="https://user-images.githubusercontent.com/109105178/221374146-c330c21f-fe81-4ff8-a152-d0dad449ee67.png">

**Comment by agsmartwolf** [comment]
@rodrigoddalmeida Do you have any thoughts?

**Comment by rodrigoddalmeida** [comment]
@agsmartwolf the playground is a good indicator that your schema is being correctly built and have all fields available. 

In that case it seems there might be an issue with how `@graphql-codegen/*` packages are interacting with each other. I would suggest doing a full clean up of your node_modules (and possibly npm's cache) and reinstall your dependencies.

**Comment by agsmartwolf** [comment]
It doesn't help =(

**Comment by rodrigoddalmeida** [comment]
> It doesn't help =(

I wish I could give more insight into the error, but additional information seems to be blocked by the missing `pluginHelpers.isDetailedError` call, which is a `@graphql-codegen` responsibility. Maybe you could monkey-patch your local dependency to extract out the error message there, before the error happens.

If you happen to fix that at some point, let me know.

**Comment by agsmartwolf** [comment]
How can I open permission for the field `product.variants.results.active`?
I've tried all of the option I could imagine:

```
{
  "parent_id": "blabla",
  "public": "pk",
  "date_created": "2022-07-10T18:09:25.254Z",
  "scope": "user",
  "revoked": false,
  "date_updated": "2023-03-08T15:58:17.174Z",
  "permissions": {
    "categories": {
      "fields": [
        "id"
      ]
    },
    "products": {
      "fields": [
        ":variants.active",
        "variants.active",
        "variants.results.active",
        "options.active"
      ]
    },
    "product": {
      "fields": [
        "active",
        "variants.active",
        "variants.results.active"
      ]
    },
    "products:variants": {
      "fields": [
        "active",
        "variants.active",
        "variants.results.active",
        "options.active"
      ]
    },
    "variant": {
      "fields": [
        "active"
      ]
    },
    "ProductsVariants": {
      "fields": [
        "active"
      ]
    },
    "variants": {
      "fields": [
        "active"
      ]
    }
  },
  "id": "blabla"
}
```

**Comment by agsmartwolf** [comment]
I've sent the PUT request with the payload you provided. I have next response:
<img width="809" alt="Screenshot 2023-03-09 at 17 47 32" src="https://user-images.githubusercontent.com/109105178/224044825-ccad8f69-d4d9-4f9a-bf35-80ae961f23f7.png">

I tried to send an empty array for the field `fields` for other models I've updated before, but it's not updated.


So by the next step, I've set a `Cache-Control` header as you said but I still have the problem:
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/109105178/224044566-dee5f2eb-0435-4c65-afa6-c9b7521e8ea4.png">

**Comment by agsmartwolf** [comment]
About `@graphql-codegen` and categories `id` field.
I've re-updated the package and now it shows the error in the next way:
<img width="1305" alt="Screenshot 2023-03-09 at 23 53 11" src="https://user-images.githubusercontent.com/109105178/224138891-2361cdd7-f967-4ac0-8985-e65866ef9302.png">

Moreover in playground with cache control is working perfect:
<img width="957" alt="image" src="https://user-images.githubusercontent.com/109105178/224139463-949558cc-14ff-4f3f-8faa-8c19fe631851.png">


But if I remove the cache control header, remove the`id` field - send request, then return `id` field and send the request again - an error is returned!
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/109105178/224139772-64703e1f-ee2a-4dcf-a1b8-a1e6b5a06cdc.png">

**Comment by rodrigoddalmeida** [comment]
> I've sent the PUT request with the payload you provided. I have next response: <img alt="Screenshot 2023-03-09 at 17 47 32" width="809" src="https://user-images.githubusercontent.com/109105178/224044825-ccad8f69-d4d9-4f9a-bf35-80ae961f23f7.png">
> 
> I tried to send an empty array for the field `fields` for other models I've updated before, but it's not updated.
> 
> So by the next step, I've set a `Cache-Control` header as you said but I still have the problem: <img alt="image" width="1727" src="https://user-images.githubusercontent.com/109105178/224044566-dee5f2eb-0435-4c65-afa6-c9b7521e8ea4.png">

It seems you are trying to access `active` on the `SwellProductVariants` type, which is a Page type and should not contain that field. It should be accessible within `results` (`SwellProductVariant` type), though:

```gql
query {  
  ...
  variants {
    results {
      active
    }
  }
}
```

**Comment by agsmartwolf** [comment]
Unfortunately it doesn't work:
<img width="1911" alt="image" src="https://user-images.githubusercontent.com/109105178/224249796-c8e30c26-ac1f-4c5e-875b-c37e48e92b08.png">

**Comment by agsmartwolf** [comment]
OMG!
About `products.variants.results.active` - it worked. I have multiple public keys and had changed permissions for another one... So I used the right internal id for the PK I use, and it worked fine.

About codegen I could resolve it too!
I've changed `codegen.yml` to the next:

![Uploading Screenshot 2023-03-10 at 18.15.49.png…]()
