### ISSUE TITLE
When will Horizon release to the UI?

### ISSUE THREAD

**Issue by thelaith** [swellstores/horizon#39]
Hey folks, 

Curious when this theme will be available to pick from the theme editor, or is that maybe not part of the plan? Reading it was supposed to be released Q3 2022.

https://www.swell.is/blog/announcing-horizon-theme

**Comment by ericingram** [comment]
Plans for our current theme editor have changed a bit and it's likely we will deprecate it in the near future, in favor of streamlining the effort to host Horizon (or any other storefront app) with a service like Vercel or Netlify. Most Swell users already do it that way.

Stay tuned for an update on those plans.

**Comment by thelaith** [comment]
Thanks for clarifying!
