### ISSUE TITLE
Attribute Id is always "null"

### ISSUE THREAD

**Issue by agsmartwolf** [swellstores/horizon#40]
Hi,

I have a query 
```
query getProduct($slug: String, $currency: String, $locale: String) {
  productBySlug(slug: $slug, _currency: $currency, _locale: $locale) {
    slug
    id
    name
    options {
      id
      attributeId
      name
      values {
        id
        name
        price
      }
    }
    stockLevel
  }
}
```

The field `attributeId` is always null right now. 
There are no ways to detect what is particular attribute id is.

I have custom components depending on attribute id.
For example I have a custom "ProductColorOption" - not Select as a default component for all of the options right now.

I could detect what is exactly option attribute before by field `attributeId`. Now it's always nullable.

Notice: it was okay before. It started to happen probably 1.5-2 weeks ago.

<img width="1716" alt="Screenshot 2023-03-06 at 20 49 32" src="https://user-images.githubusercontent.com/109105178/223739555-b4820125-5525-4239-a997-8dd7604f2911.png">

**Comment by rodrigoddalmeida** [comment]
Hi @agsmartwolf, since this looks related to our API, we'll keep track of the issue in your Discussions post: https://github.com/orgs/swellstores/discussions/166. Closing this one.
