### ISSUE TITLE
npm install error on local machine

### ISSUE THREAD

**Issue by rishiimmehra** [swellstores/horizon#43]
$ npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: relay-compiler@12.0.0
npm WARN Found: graphql@16.3.0
npm WARN node_modules/graphql
npm WARN   graphql@"^16.3.0" from the root project
npm WARN   69 more (@graphql-codegen/cli, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer graphql@"^15.0.0" from relay-compiler@12.0.0
npm WARN node_modules/relay-compiler
npm WARN   relay-compiler@"12.0.0" from @graphql-tools/relay-operation-optimizer@6.4.5
npm WARN   node_modules/@graphql-tools/relay-operation-optimizer
npm WARN
npm WARN Conflicting peer dependency: graphql@15.8.0
npm WARN node_modules/graphql
npm WARN   peer graphql@"^15.0.0" from relay-compiler@12.0.0
npm WARN   node_modules/relay-compiler
npm WARN     relay-compiler@"12.0.0" from @graphql-tools/relay-operation-optimizer@6.4.5
npm WARN     node_modules/@graphql-tools/relay-operation-optimizer
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: webpack-filter-warnings-plugin@1.2.1
npm WARN Found: webpack@5.70.0
npm WARN node_modules/webpack
npm WARN   dev webpack@"^5.69.1" from the root project
npm WARN   24 more (@pmmmwh/react-refresh-webpack-plugin, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer webpack@"^2.0.0 || ^3.0.0 || ^4.0.0" from webpack-filter-warnings-plugin@1.2.1
npm WARN node_modules/webpack-filter-warnings-plugin
npm WARN   webpack-filter-warnings-plugin@"^1.2.1" from @storybook/builder-webpack4@6.5.10
npm WARN   node_modules/@storybook/builder-webpack4
npm WARN
npm WARN Conflicting peer dependency: webpack@4.46.0
npm WARN node_modules/webpack
npm WARN   peer webpack@"^2.0.0 || ^3.0.0 || ^4.0.0" from webpack-filter-warnings-plugin@1.2.1
npm WARN   node_modules/webpack-filter-warnings-plugin
npm WARN     webpack-filter-warnings-plugin@"^1.2.1" from @storybook/builder-webpack4@6.5.10
npm WARN     node_modules/@storybook/builder-webpack4

> @swell/horizon@0.4.0 prepare
> husky install && if [ -f codegen.yml ] && [ -f build-utils/generate-theme.mjs ]; then npm run setup; fi

-f was unexpected at this time.
npm ERR! code 1
npm ERR! path C:\Users\home\Desktop\SWELL\onegetup
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c husky install && if [ -f codegen.yml ] && [ -f build-utils/generate-theme.mjs ]; then npm run setup; fi

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\home\AppData\Local\npm-cache\_logs\2023-03-26T07_38_04_644Z-debug-0.log

**Comment by codeclouds-team** [comment]
Have you got any solution yet @rishiimmehra ?

**Comment by ericingram** [comment]
Maybe @rodrigoddalmeida or @logeshswell can advise

**Comment by unknownsouls** [comment]
can't install either!

**Comment by sags95** [comment]
@rishiimmehra The latest version of Horizon now includes fixes to a lot of the issues mentioned in this thread. Please pull the latest changes and run npm install , you'll also have to create a SWELL_STOREFRONT_ID env var. More info can be found [here](https://developers.swell.is/storefronts/horizon).

**Comment by sags95** [comment]
@rishiimmehra The latest version of Horizon now includes fixes to a lot of the issues mentioned in this thread. Please pull the latest changes and run npm install , you'll also have to create a SWELL_STOREFRONT_ID env var. More info can be found [here](https://developers.swell.is/storefronts/horizon).
