### ISSUE TITLE
Unable to setup on local machine (npm install is erroring out)

### ISSUE THREAD

**Issue by varmab** [swellstores/horizon#44]
husky - Git hooks installed

> @swell/horizon@0.4.0 setup
> npm run sync && npm run graphql:generate && npm run theme:generate

> @swell/horizon@0.4.0 sync
> set -a && if [ -f .env ]; then source .env; fi && npm run sync:defaults && npm run sync:content-blocks && npm run sync:editor

> @swell/horizon@0.4.0 sync:defaults
> swell storefront settings push settings -f ./config/defaults.json --strategy "defaults" --store $SWELL_STORE_ID --secret-key $SWELL_SECRET_KEY

✖ 401 Authentication failed (client: jmFMWKgV)

I put all things correctly in .env file 

Any idea what might be the issue?

**Comment by sags95** [comment]
@varmab Please checkout this reply here: https://github.com/orgs/swellstores/discussions/258#discussioncomment-6015352

**Comment by sags95** [comment]
The latest version of Horizon now includes fixes to a lot of the issues mentioned in this thread. Please pull the latest changes and run npm install , you'll also have to create a SWELL_STOREFRONT_ID env var. More info can be found [here](https://developers.swell.is/storefronts/horizon).
