### ISSUE TITLE
ERROR 404 Page not found

### ISSUE THREAD

**Issue by racsou** [swellstores/horizon#46]
![Capture](https://github.com/swellstores/horizon/assets/120835349/f231cad7-3d5a-4153-8a6d-24b14177168f)
how can i SOLVE THIS I'm getting this error in the home page

**Comment by sebelapetr** [comment]
Hi, I'v got same problem. Almost nothing is working. Probably because I created swell store after storefronts in Swell dashboard with editor were removed, so I'm missing pages etc. Are you preparing some version for new users who has new stores without storefront editor?

**Comment by ralphilius** [comment]
@sags95 I'm using that version but I still see the 404 not found page at home. The preview page is not showing either.
