### ISSUE TITLE
Menu updates aka whac-a-mole.

### ISSUE THREAD

**Issue by holden** [swellstores/horizon#48]
Hi.

I'm not sure if this is specific to horizon or not but I'm having a problem with changing settings related to the theme and menus.

Specifically when I edit the navigations, changes I make tend to undo other changes. Eg if I try to add a footer, it removes the header and vice versa. Sometimes when I try to add the header back it removes the footer and the header.

I know both my header and footers work, but I can't seem to get these changes saved at the same times.

Is there some setting I don't have correct setup that would cause this issue?

I made a video:

https://github.com/swellstores/horizon/assets/48241/c4cc116f-0091-45ed-a72e-f326ff54a83a

**Comment by holden** [comment]
I figured it out, apparently I had "All categories" in the menu which for whatever reason causes a 404 which I found in the console. Once I removed it from the menu it works again.

**Comment by holden** [comment]
After I had figured it out, they both promptly stopped working again while I was making a few very small changes only within the storefront theme editor, this time with no errors in the console. In this instance I added social icons after which both menus seem to start appearing although I can get them to appear temporarily but even loading the editor can cause both to disappear again.

Is there some way I can debug whatever is going on?  It's like there's a small demon inside the storefront editor, I would be terrified to make any changes if this were in production.  What could cause this?

**Comment by logeshswell** [comment]
Added the response to this issue in the below Github discussion thread
https://github.com/orgs/swellstores/discussions/271#discussioncomment-6303390

**Comment by logeshswell** [comment]
@holden Responded to this issue in the below GitHub discussion thread:
https://github.com/orgs/swellstores/discussions/271#discussioncomment-6303390

I will keep you posted if this bug is resolved.

**Comment by logeshswell** [comment]
This issue is fixed and deployed in production. Please check and confirm.
