### ISSUE TITLE
Cloudflare Pages support?

### ISSUE THREAD

**Issue by ralphilius** [swellstores/horizon#49]
Hello,

I'm trying to deploy on Cloudflare Pages, but it seems we need to add Edge Runtime config in `api` pages. I can make a PR to add the flag in each of the routes in `api` folder if you think it's good enough.

**Comment by fucha-co** [comment]
i'm currently looking into using Swell + Cloudflare Pages and had read in the Swell Docs that [Cloudflare Pages is supported](https://developers.swell.is/storefronts/storefront-hosting/storefronts-on-cloudflare-pages). So I'd love to know what the official status is? Did you get Swell working with CFP @ralphilius?

**Comment by ericingram** [comment]
cc @logeshswell

**Comment by logeshswell** [comment]
@fucha-co @ralphilius We have a Github discussion to deploy swell storefronts in Cloudflare. I can also confirm that a few merchants are hosting their Swell storefronts via Cloudflare without any issues.

If you face any issues, please feel free to start a new thread in the below discussion. I am very happy to answer you.
https://github.com/orgs/swellstores/discussions/279
